 var idslct = charIDToTypeID("slct");
    var desc15622 = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var ref474 = new ActionReference();
    var idLyr = charIDToTypeID("Lyr ");
    var idOrdn = charIDToTypeID("Ordn");
    var idBckw = charIDToTypeID("Bckw");
    ref474.putEnumerated(idLyr, idOrdn, idBckw);
    desc15622.putReference(idnull, ref474);
    var idMkVs = charIDToTypeID("MkVs");
    desc15622.putBoolean(idMkVs, false);
    var idLyrI = charIDToTypeID("LyrI");
    var list249 = new ActionList();
    list249.putInteger(8);
    desc15622.putList(idLyrI, list249);
    executeAction(idslct, desc15622, DialogModes.NO);