var nameLayer = "WALL4";
var feather = 1;
const expandSelection = 1;
const nameChannel = "Wall";
var nameTxtLV = "/levelColor4.txt";
const opacityValue = 100;
var middleLevelsValue = 1;
var destWhiteMin = 180;
var nameJsonColor = "/color4.json";
$.evalFile(currentFolder + "/setcolor.jsx");
