var fixColor = false;
var nameLayer = "WALL3";
var feather = 1;
const nameChannel = "Wall";
var nameTxtLV = "/levelColor3.txt";
const opacityValue = 100;
var middleLevelsValue = 1;
var destWhiteMin = 180;
var nameJsonColor = "/color3.json";
$.evalFile(currentFolder + "/setcolor.jsx");
