var nameLayer = "WALL2";
var feather = 1;
const expandSelection = 1;
const nameChannel = "Wall";
var nameTxtLV = "/levelColor2.txt";
const opacityValue = 100;
var middleLevelsValue = 1;
var destWhiteMin = 180;
var nameJsonColor = "/color2.json";
$.evalFile(currentFolder + "/setcolor.jsx");